name: 'ShellCheck'

on:
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    env:
      SHELLCHECK_OPTS: -s bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.8.0
          format: tty
