name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test-simple:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: simple
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-readme:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: readme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-octicons:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: octicons
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-mojombo:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: mojombo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-themes:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: themes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-jekyll-include-cache:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: jekyll-include-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-future-false:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: future-false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}

  test-future-true:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: future-true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          build_revision: JEKYLL_BUILD_REVISION
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify output
        run: |
          ./bin/compare_expected_output ./test_projects/${{env.TEST_NAME}}
